FROM node:lts-alpine as build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install @vue/cli@5.0.8 -g
COPY package.json .
COPY package-lock.json .
RUN npm install
RUN npm run build

FROM bitnami/nginx:latest
COPY --from=build-stage /app/dist /app