services:
  backend:
    container_name: rim-backend
    image: zeroglatte/rim-backend:latest
    env_file:
      - ./backend/.env
    environment:
      - VIRTUAL_HOST=api.zerog.cc
    ports:
      - 5000:8080
